### ISSUE TITLE
Failed to to call /addons/1a422d19_fuxa-slr/install - The command '/bin/sh -c npm install' returned a non-zero code: 1

### ISSUE THREAD

**Issue by Alech385** [SmartLiving-Rocks/FUXA_HomeAssistant_Addon#1]
Hello,

When I try to install the addon in HASS I get every time the error: 

Failed to to call /addons/1a422d19_fuxa-slr/install - The command '/bin/sh -c npm install' returned a non-zero code: 1

What am I doing wrong?

**Comment by SmartLiving-Rocks** [comment]
Your Hardware is not supported. 

What are you using as a Home Assistant Server?

I have an ASUS Tinker Board that also gives me the error. 


<img width="859" alt="Bildschirmfoto 2024-04-27 um 17 05 14" src="https://github.com/SmartLiving-Rocks/FUXA/assets/76279896/fab21281-9c03-4628-b2ce-0a63af95314f">

<img width="488" alt="Bildschirmfoto 2024-04-27 um 17 08 27" src="https://github.com/SmartLiving-Rocks/FUXA/assets/76279896/05fb32dc-6ae4-490a-8fa9-4ed3c752e60e">

**Comment by Alech385** [comment]
I use a RPI4-64 with 4GB.

**Comment by michaeltanner70** [comment]
Same problem here after upgrade to 12.4 OS and Core 6.4. Rebuild also not possible. Runs on raspberry CM4. Worked fine before

**Comment by tziku** [comment]
Same problem when try to install on RPI4-64.
Core 2024.12.3
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.8




2024-12-14 22:09:00.477 ERROR (MainThread) [supervisor.docker.addon] Can't build 1a422d19/aarch64-addon-fuxa-slr:1.0.1: The command '/bin/sh -c npm install' returned a non-zero code: 1
2024-12-14 22:09:00.478 ERROR (MainThread) [supervisor.docker.addon] Build log: 
Step 1/16 : FROM node:14
 ---> b6e1f9016a80
Step 2/16 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 60705c686f3e
Step 3/16 : RUN git clone https://github.com/frangoteam/FUXA.git
 ---> Using cache
 ---> ecf9c111ac09
Step 4/16 : WORKDIR /usr/src/app/FUXA
 ---> Using cache
 ---> 53cbce604e2a
Step 5/16 : WORKDIR /usr/src/app/FUXA/server
 ---> Using cache
 ---> 2ac059962823
Step 6/16 : RUN npm install
 ---> Running in 17b1b9d1537b
> @serialport/bindings-cpp@12.0.1 install /usr/src/app/FUXA/server/node_modules/@serialport/bindings-cpp
> node-gyp-build
> odbc@2.4.9 install /usr/src/app/FUXA/server/node_modules/odbc
> node-pre-gyp install --fallback-to-build
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/IBM/node-odbc/releases/download/v2.4.9/odbc-v2.4.9-linux-arm64-napi-v8.tar.gz 
node-pre-gyp WARN
 Pre-built binaries not installable for odbc@2.4.9 and node@14.21.3 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN
 Hit error response status 404 Not Found on https://github.com/IBM/node-odbc/releases/download/v2.4.9/odbc-v2.4.9-linux-arm64-napi-v8.tar.gz
 
make: Entering directory '/usr/src/app/FUXA/server/node_modules/odbc/build'
  CXX(target) Release/obj.target/odbc/src/odbc.o
In file included from ../src/odbc.cpp:22:
../src/odbc.h:37:10: fatal error: sql.h: No such file or directory
 #include <sql.h>
          ^~~~~~~
compilation terminated.
make: Leaving directory '/usr/src/app/FUXA/server/node_modules/odbc/build'
make: *** [odbc.target.mk:125: Release/obj.target/odbc/src/odbc.o] Error 1
gyp
 ERR! build error 
gyp 
ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack
     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack
     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System
 Linux 6.6.51-haos-raspi
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/src/app/FUXA/server/node_modules/odbc/lib/bindings/napi-v8/odbc.node" "--module_name=odbc" "--module_path=/usr/src/app/FUXA/server/node_modules/odbc/lib/bindings/napi-v8" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=8" "--node_napi_label=napi-v8"
gyp 
ERR! cwd /usr/src/app/FUXA/server/node_modules/odbc
gyp
 ERR! 
node -v
 v14.21.3
gyp ERR! 
node-gyp -v v5.1.1
gyp ERR! 
not ok 
node-pre-gyp 
ERR! build error
 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/src/app/FUXA/server/node_modules/odbc/lib/bindings/napi-v8/odbc.node --module_name=odbc --module_path=/usr/src/app/FUXA/server/node_modules/odbc/lib/bindings/napi-v8 --napi_version=8 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1)
node-pre-gyp 
ERR! stack     at ChildProcess.<anonymous> (/usr/src/app/FUXA/server/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack
     at ChildProcess.emit (events.js:400:28)
node-pre-gyp
 ERR! stack     at maybeClose (internal/child_process.js:1088:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
node-pre-gyp ERR!
 System
 Linux 6.6.51-haos-raspi
node-pre-gyp ERR!
 
command "/usr/local/bin/node" "/usr/src/app/FUXA/server/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR!
 cwd /usr/src/app/FUXA/server/node_modules/odbc
node-pre-gyp ERR!
 node -v
 v14.21.3
node-pre-gyp ERR!
 node-pre-gyp -v v1.0.11
node-pre-gyp ERR!
 
not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/src/app/FUXA/server/node_modules/odbc/lib/bindings/napi-v8/odbc.node --module_name=odbc --module_path=/usr/src/app/FUXA/server/node_modules/odbc/lib/bindings/napi-v8 --napi_version=8 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm ERR! code ELIFECYCLE
npm ERR! 
errno 1
npm ERR! odbc@2.4.9 install: `node-pre-gyp install --fallback-to-build`
npm
 ERR! Exit status 1
npm ERR! 
npm 
ERR! Failed at the odbc@2.4.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm 
ERR! A complete log of this run can be found in:
npm ERR!
     /root/.npm/_logs/2024-12-14T20_08_54_425Z-debug.log
 ---> Removed intermediate container 17b1b9d1537b
2024-12-14 22:09:00.688 INFO (MainThread) [supervisor.docker.addon] Starting build for 1a422d19/aarch64-addon-fuxa-slr:1.0.1
2024-12-14 22:10:06.284 ERROR (MainThread) [supervisor.docker.addon] Can't build 1a422d19/aarch64-addon-fuxa-slr:1.0.1: The command '/bin/sh -c npm install' returned a non-zero code: 1
2024-12-14 22:10:06.285 ERROR (MainThread) [supervisor.docker.addon] Build log: 
Step 1/16 : FROM node:14
 ---> b6e1f9016a80
Step 2/16 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 60705c686f3e
Step 3/16 : RUN git clone https://github.com/frangoteam/FUXA.git
 ---> Using cache
 ---> ecf9c111ac09
Step 4/16 : WORKDIR /usr/src/app/FUXA
 ---> Using cache
 ---> 53cbce604e2a
Step 5/16 : WORKDIR /usr/src/app/FUXA/server
 ---> Using cache
 ---> 2ac059962823
Step 6/16 : RUN npm install
 ---> Running in f9e7cb88a1d3
> @serialport/bindings-cpp@12.0.1 install /usr/src/app/FUXA/server/node_modules/@serialport/bindings-cpp
> node-gyp-build
> odbc@2.4.9 install /usr/src/app/FUXA/server/node_modules/odbc
> node-pre-gyp install --fallback-to-build
node-pre-gyp
 ERR! install response status 404 Not Found on https://github.com/IBM/node-odbc/releases/download/v2.4.9/odbc-v2.4.9-linux-arm64-napi-v8.tar.gz 
node-pre-gyp
 WARN Pre-built binaries not installable for odbc@2.4.9 and node@14.21.3 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/IBM/node-odbc/releases/download/v2.4.9/odbc-v2.4.9-linux-arm64-napi-v8.tar.gz 
make: Entering directory '/usr/src/app/FUXA/server/node_modules/odbc/build'
  CXX(target) Release/obj.target/odbc/src/odbc.o
In file included from ../src/odbc.cpp:22:
../src/odbc.h:37:10: fatal error: sql.h: No such file or directory
 #include <sql.h>
          ^~~~~~~
compilation terminated.
make: *** [odbc.target.mk:125: Release/obj.target/odbc/src/odbc.o] Error 1
gyp ERR! build error 
make: Leaving directory '/usr/src/app/FUXA/server/node_modules/odbc/build'
gyp 
ERR!
 stack
 Error: `make` failed with exit code: 2
gyp
 ERR!
 stack
     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp 
ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
gyp ERR! System Linux 6.6.51-haos-raspi
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/src/app/FUXA/server/node_modules/odbc/lib/bindings/napi-v8/odbc.node" "--module_name=odbc" "--module_path=/usr/src/app/FUXA/server/node_modules/odbc/lib/bindings/napi-v8" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=8" "--node_napi_label=napi-v8"
gyp ERR! 
cwd /usr/src/app/FUXA/server/node_modules/odbc
gyp ERR! node -v
 v14.21.3
gyp ERR! 
node-gyp -v v5.1.1
gyp ERR! not ok 
node-pre-gyp ERR! 
build error 
node-pre-gyp 
ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/src/app/FUXA/server/node_modules/odbc/lib/bindings/napi-v8/odbc.node --module_name=odbc --module_path=/usr/src/app/FUXA/server/node_modules/odbc/lib/bindings/napi-v8 --napi_version=8 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/src/app/FUXA/server/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
node-pre-gyp
 ERR! stack     at maybeClose (internal/child_process.js:1088:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
node-pre-gyp ERR! System Linux 6.6.51-haos-raspi
node-pre-gyp ERR!
 command "/usr/local/bin/node" "/usr/src/app/FUXA/server/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/src/app/FUXA/server/node_modules/odbc
node-pre-gyp 
ERR! 
node -v v14.21.3
node-pre-gyp ERR! node-pre-gyp -v
 v1.0.11
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/src/app/FUXA/server/node_modules/odbc/lib/bindings/napi-v8/odbc.node --module_name=odbc --module_path=/usr/src/app/FUXA/server/node_modules/odbc/lib/bindings/napi-v8 --napi_version=8 --node_abi_napi=napi --napi_build_version=8 --node_napi_label=napi-v8' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.3 (node_modules/fsevents):
npm WARN
 notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm64"})
npm ERR! code ELIFECYCLE
npm ERR! 
errno 1
npm ERR! odbc@2.4.9 install: `node-pre-gyp install --fallback-to-build`
npm
 ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the odbc@2.4.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm 
ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-12-14T20_10_02_791Z-debug.log
 ---> Removed intermediate container f9e7cb88a1d3

**Comment by praktikon** [comment]
I have the same problem
raspberry pi 5
 System: Home Assistant OS 14.1  (aarch64 / raspberrypi5-64)
 Home Assistant Core: 2025.1.4
 Home Assistant Supervisor: 2024.12.3

**Comment by Knipex95** [comment]
Hello together
I have the home assistant green and the same problem.

Witch devices are supportet for FUXA? 

Have a nice day :)

**Comment by SmartLiving-Rocks** [comment]
Just installed it on a Pi 5.
Please check if it is also working for you
